/**
 * Orbit X3DH — Extended Triple Diffie-Hellman Key Agreement
 *
 * Implements the X3DH protocol (Signal specification) adapted for Web Crypto API.
 *
 * KEY TYPES:
 *   - Identity Key  (IK): Long-term ECDH P-256 key (stored in keyStore)
 *   - Signed Prekey (SPK): Medium-term ECDH key, signed by IK using ECDSA P-256
 *   - One-Time Prekey (OPK): Per-session ephemeral ECDH key (consumed on use)
 *   - Ephemeral Key (EK): Per-handshake ephemeral ECDH key (generated by Alice)
 *
 * NOTE: We use ECDSA P-256 for signing instead of Ed25519 because Web Crypto
 * does not expose Ed25519 on all platforms. Both curves provide equivalent
 * 128-bit security for this use case.
 *
 * HANDSHAKE (Alice → Bob):
 *   1. Alice fetches Bob's prekey bundle: { IK_B, SPK_B, sig_B, OPK_B? }
 *   2. Alice verifies SPK_B signature against IK_B
 *   3. Alice generates ephemeral key EK_A
 *   4. Alice computes:
 *        DH1 = ECDH(IK_A_priv, SPK_B_pub)
 *        DH2 = ECDH(EK_A_priv, IK_B_pub)
 *        DH3 = ECDH(EK_A_priv, SPK_B_pub)
 *        DH4 = ECDH(EK_A_priv, OPK_B_pub)  [if OPK available]
 *        SK  = HKDF(DH1 || DH2 || DH3 || DH4)
 *   5. Alice sends: { IK_A_pub, EK_A_pub, OPK_B_id, initialCiphertext }
 *
 *   Bob mirrors the process to derive the same SK.
 *   SK becomes the Double Ratchet root key.
 */

// ── Helpers ──────────────────────────────────────────────────────────────────

const buf2b64 = (buf) => btoa(String.fromCharCode(...new Uint8Array(buf)));
const b64toBuf = (b64) => {
  const bin = atob(b64);
  const buf = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) buf[i] = bin.charCodeAt(i);
  return buf.buffer;
};

const ECDH_PARAMS  = { name: "ECDH",  namedCurve: "P-256" };
const ECDSA_PARAMS = { name: "ECDSA", namedCurve: "P-256" };
const HKDF_HASH    = "SHA-256";
const X3DH_INFO    = new TextEncoder().encode("orbit-x3dh-v1");
const X3DH_SALT    = new Uint8Array(32); // 32 zero bytes (per Signal spec)

// ── Key generation ─────────────────────────────────────────────────────────────

/**
 * Generate a new ECDH P-256 key pair (for IK, SPK, OPK, EK).
 * Returns { publicKey: extractable CryptoKey, privateKey: non-extractable CryptoKey }
 */
export const generateECDHKeyPair = () =>
  crypto.subtle.generateKey(ECDH_PARAMS, false, ["deriveKey", "deriveBits"]);

/**
 * Generate a new ECDSA P-256 key pair (for signing SPK).
 * The signing private key must be non-extractable.
 */
export const generateSigningKeyPair = () =>
  crypto.subtle.generateKey(ECDSA_PARAMS, false, ["sign", "verify"]);

/**
 * Sign a public key buffer with an ECDSA private key.
 * @param {ArrayBuffer} dataBuffer - The raw data to sign (e.g. SPK public key SPKI bytes)
 * @param {CryptoKey} signingPrivateKey - ECDSA signing key
 * @returns {Promise<string>} base64 DER signature
 */
export const signKey = async (dataBuffer, signingPrivateKey) => {
  const sig = await crypto.subtle.sign(
    { name: "ECDSA", hash: "SHA-256" },
    signingPrivateKey,
    dataBuffer
  );
  return buf2b64(sig);
};

/**
 * Verify a signed prekey signature.
 * @param {ArrayBuffer} dataBuffer - The signed data (SPK public key SPKI bytes)
 * @param {string} signatureB64 - base64 signature
 * @param {CryptoKey} verifyingPublicKey - ECDSA public key (from IK)
 * @returns {Promise<boolean>}
 */
export const verifyKeySignature = async (dataBuffer, signatureB64, verifyingPublicKey) => {
  try {
    return await crypto.subtle.verify(
      { name: "ECDSA", hash: "SHA-256" },
      verifyingPublicKey,
      b64toBuf(signatureB64),
      dataBuffer
    );
  } catch {
    return false;
  }
};

// ── Key export/import ─────────────────────────────────────────────────────────

/** Export an ECDH public key as base64 SPKI */
export const exportPublicKey = async (key) => buf2b64(await crypto.subtle.exportKey("spki", key));

/** Export an ECDSA public key as base64 SPKI */
export const exportSigningPublicKey = async (key) => buf2b64(await crypto.subtle.exportKey("spki", key));

/** Import a base64 SPKI ECDH public key */
export const importECDHPublicKey = (b64) =>
  crypto.subtle.importKey("spki", b64toBuf(b64), ECDH_PARAMS, true, []);

/** Import a base64 SPKI ECDSA public key */
export const importSigningPublicKey = (b64) =>
  crypto.subtle.importKey("spki", b64toBuf(b64), ECDSA_PARAMS, true, ["verify"]);

// ── Core DH + KDF ─────────────────────────────────────────────────────────────

/**
 * Perform ECDH and return raw shared bits (256 bits).
 * @param {CryptoKey} privateKey - Our ECDH private key
 * @param {CryptoKey} publicKey  - Their ECDH public key
 * @returns {Promise<ArrayBuffer>} 32 bytes of shared secret material
 */
const dh = async (privateKey, publicKey) =>
  crypto.subtle.deriveBits({ name: "ECDH", public: publicKey }, privateKey, 256);

/**
 * Derive the shared session key (SK) from concatenated DH outputs.
 * Per X3DH spec: SK = KDF(DH1 || DH2 || DH3 || DH4?)
 * @param {ArrayBuffer[]} dhOutputs - Array of 32-byte DH results
 * @returns {Promise<ArrayBuffer>} 32-byte SK
 */
const deriveSessionKey = async (dhOutputs) => {
  const combined = new Uint8Array(dhOutputs.reduce((acc, b) => acc + b.byteLength, 0));
  let offset = 0;
  for (const buf of dhOutputs) {
    combined.set(new Uint8Array(buf), offset);
    offset += buf.byteLength;
  }

  const ikm = await crypto.subtle.importKey("raw", combined, { name: "HKDF" }, false, ["deriveBits"]);
  const skBits = await crypto.subtle.deriveBits(
    { name: "HKDF", hash: HKDF_HASH, salt: X3DH_SALT, info: X3DH_INFO },
    ikm,
    256
  );
  return skBits;
};

// ── X3DH Sender (Alice) ───────────────────────────────────────────────────────

/**
 * Perform X3DH key agreement as the initiating party (Alice/sender).
 *
 * @param {object} params
 * @param {CryptoKey} params.senderIdentityPrivateKey  - Alice's IK private key
 * @param {object}   params.recipientBundle             - Bob's prekey bundle from server
 * @param {string}   params.recipientBundle.identityKey    - IK_B base64 SPKI
 * @param {string}   params.recipientBundle.signedPrekey   - SPK_B base64 SPKI
 * @param {string}   params.recipientBundle.prekeySignature - signature on SPK_B
 * @param {string}   [params.recipientBundle.oneTimePrekey] - OPK_B base64 SPKI
 * @param {string}   [params.recipientBundle.oneTimePrekeyId] - OPK_B identifier
 * @param {string}   params.recipientBundle.signingKey    - IK_B ECDSA pub key base64 SPKI
 *
 * @returns {Promise<{
 *   sessionKey: ArrayBuffer,   // 32-byte shared secret (→ Double Ratchet root key)
 *   ephemeralPublicKey: string, // EK_A base64 SPKI (send to Bob)
 *   oneTimePrekeyId: string|null // which OPK was used
 * }>}
 * @throws if SPK signature verification fails
 */
export const x3dhSender = async ({ senderIdentityPrivateKey, recipientBundle }) => {
  const {
    identityKey: ikB_b64,
    signedPrekey: spkB_b64,
    prekeySignature: sigB_b64,
    oneTimePrekey: opkB_b64,
    oneTimePrekeyId,
    signingKey: sigKeyB_b64,
  } = recipientBundle;

  // 1. Import Bob's keys
  const IK_B  = await importECDHPublicKey(ikB_b64);
  const SPK_B = await importECDHPublicKey(spkB_b64);
  const SIG_B = await importSigningPublicKey(sigKeyB_b64 || ikB_b64);

  // 2. Verify SPK_B signature — ABORT if invalid (potential MITM)
  const spkBuf = b64toBuf(spkB_b64);
  const isValid = await verifyKeySignature(spkBuf, sigB_b64, SIG_B);
  if (!isValid) {
    throw new Error("[X3DH] SPK signature verification FAILED. Potential MITM attack. Aborting handshake.");
  }

  // 3. Generate Alice's ephemeral key pair
  const EK_A = await generateECDHKeyPair();

  // 4. Compute DH values
  const DH1 = await dh(senderIdentityPrivateKey, SPK_B);   // IK_A × SPK_B
  const DH2 = await dh(EK_A.privateKey, IK_B);              // EK_A × IK_B
  const DH3 = await dh(EK_A.privateKey, SPK_B);             // EK_A × SPK_B

  const dhOutputs = [DH1, DH2, DH3];

  let usedOPKId = null;
  if (opkB_b64) {
    const OPK_B = await importECDHPublicKey(opkB_b64);
    const DH4 = await dh(EK_A.privateKey, OPK_B);            // EK_A × OPK_B
    dhOutputs.push(DH4);
    usedOPKId = oneTimePrekeyId || null;
  }

  // 5. Derive session key
  const sessionKey = await deriveSessionKey(dhOutputs);

  // 6. Export ephemeral public key to send to Bob
  const ephemeralPublicKey = await exportPublicKey(EK_A.publicKey);

  return { sessionKey, ephemeralPublicKey, oneTimePrekeyId: usedOPKId };
};

// ── X3DH Receiver (Bob) ───────────────────────────────────────────────────────

/**
 * Perform X3DH key agreement as the receiving party (Bob).
 *
 * @param {object} params
 * @param {CryptoKey} params.recipientIdentityPrivateKey - Bob's IK private key
 * @param {CryptoKey} params.signedPrekeyPrivateKey      - Bob's SPK private key
 * @param {CryptoKey} [params.oneTimePrekeyPrivateKey]   - Bob's OPK private key (if used)
 * @param {object}   params.senderHeader                 - From Alice's initial message
 * @param {string}   params.senderHeader.identityKey     - IK_A base64 SPKI
 * @param {string}   params.senderHeader.ephemeralKey    - EK_A base64 SPKI
 *
 * @returns {Promise<ArrayBuffer>} 32-byte shared session key (same as Alice derived)
 */
export const x3dhReceiver = async ({
  recipientIdentityPrivateKey,
  signedPrekeyPrivateKey,
  oneTimePrekeyPrivateKey,
  senderHeader,
}) => {
  const { identityKey: ikA_b64, ephemeralKey: ekA_b64 } = senderHeader;

  const IK_A = await importECDHPublicKey(ikA_b64);
  const EK_A = await importECDHPublicKey(ekA_b64);

  const DH1 = await dh(signedPrekeyPrivateKey, IK_A);         // SPK_B × IK_A
  const DH2 = await dh(recipientIdentityPrivateKey, EK_A);    // IK_B  × EK_A
  const DH3 = await dh(signedPrekeyPrivateKey, EK_A);          // SPK_B × EK_A

  const dhOutputs = [DH1, DH2, DH3];

  if (oneTimePrekeyPrivateKey) {
    const DH4 = await dh(oneTimePrekeyPrivateKey, EK_A);       // OPK_B × EK_A
    dhOutputs.push(DH4);
  }

  return deriveSessionKey(dhOutputs);
};

// ── Prekey bundle generation (for upload to server) ──────────────────────────

/**
 * Generate a full prekey bundle for a user.
 * Caller must persist private keys via keyStore.js.
 *
 * @param {CryptoKey} identityPrivateKey  - User's IK private key (from keyStore)
 * @param {CryptoKey} signingPrivateKey   - User's ECDSA signing private key (from keyStore)
 * @param {number}    [numOPKs=10]        - Number of one-time prekeys to generate
 *
 * @returns {Promise<{
 *   bundle: object,   // Upload this to the server
 *   privateKeys: object  // Store these in keyStore (never expose)
 * }>}
 */
export const generatePrekeyBundle = async (identityPrivateKey, signingPrivateKey, numOPKs = 10) => {
  // 1. Generate signed prekey
  const SPK = await generateECDHKeyPair();
  const spkPub = await exportPublicKey(SPK.publicKey);
  const spkBuf = b64toBuf(spkPub);
  const spkSignature = await signKey(spkBuf, signingPrivateKey);

  // 2. Generate one-time prekeys
  const opks = [];
  const opkPrivKeys = {};
  for (let i = 0; i < numOPKs; i++) {
    const id = crypto.randomUUID();
    const OPK = await generateECDHKeyPair();
    const pub = await exportPublicKey(OPK.publicKey);
    opks.push({ id, publicKey: pub });
    opkPrivKeys[id] = OPK.privateKey;
  }

  return {
    bundle: {
      signedPrekey: spkPub,
      spkSignature,
      oneTimePrekeys: opks,
    },
    privateKeys: {
      signedPrekeyPrivate: SPK.privateKey,
      oneTimePrekeyPrivates: opkPrivKeys,
    },
  };
};
